// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/lib/dbTypes';

const SUPABASE_URL = "https://dmqaoqqjtrfnhupqnvcm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtcWFvcXFqdHJmbmh1cHFudmNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1Mjk4MDEsImV4cCI6MjA3MjEwNTgwMX0.h3KwUgv5DYAy5scz-9o1yczPMYS7er22UPRLLzPUU0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});